import { icon, escapeHtml } from './components.mjs';
import { site } from './content.mjs';

export function editorPage() {
  return `<section class="editor-intro" lang="zh-CN"><div><div class="eyebrow">YOUR NOTEBOOK</div><h1>把想法写下来<span class="sage-text">。</span></h1><p>从一段文字开始，慢慢整理成值得分享的笔记。</p></div><a href="/post/" class="text-link">查看文章 ${icon('arrow')}</a></section>
  <div id="notebook-editor" class="notebook-editor" lang="zh-CN">
    <noscript><p class="editor-notice">请启用 JavaScript 后使用编辑器。已发布文章仍可正常阅读。</p></noscript>
    <aside class="editor-sidebar"><button type="button" class="button button-primary" id="new-note">${icon('edit')}新建笔记</button><h2>我的草稿 <span id="draft-count">0</span></h2><p class="editor-hint">仅保存在当前浏览器。可下载备份。</p><div id="draft-list" class="note-list"></div><h2>已发布</h2><div id="published-list" class="note-list"><p class="editor-hint">正在读取…</p></div><label class="button button-secondary import-note" for="import-note">导入笔记备份</label><input id="import-note" type="file" accept=".json,application/json" class="sr-only"></aside>
    <section class="editor-workspace" aria-label="笔记编辑器">
      <div class="editor-actionbar"><p id="save-status" role="status">开始写作，草稿会自动保存</p><div class="editor-actions"><button type="button" class="button button-secondary" id="save-note">保存草稿</button><button type="button" class="button button-primary" id="publish-note">发布到网站 ${icon('arrow')}</button></div></div>
      <p id="editor-message" class="editor-notice" role="alert" hidden></p>
      <form id="note-form" class="card note-form">
        <label for="note-title" class="input-label">笔记标题</label><input id="note-title" class="note-title-input" maxlength="120" required placeholder="给这个想法起个名字" autocomplete="off">
        <div class="note-metadata"><div><label for="note-date" class="input-label">日期</label><input type="date" id="note-date" class="input" required></div><div><label for="note-category" class="input-label">分类</label><input id="note-category" class="input" maxlength="40" required value="Notes" list="note-categories"><datalist id="note-categories"><option value="Notes"><option value="Projects"></datalist></div><div><label for="note-tags" class="input-label">标签（逗号分隔）</label><input id="note-tags" class="input" placeholder="生活, 技术, 灵感" maxlength="410"></div></div>
        <details class="note-details"><summary>摘要与文章地址</summary><label for="note-description" class="input-label">摘要（可选）</label><textarea id="note-description" class="input" rows="2" maxlength="300" placeholder="一句话介绍这篇笔记，留空会自动摘取正文"></textarea><label for="note-slug" class="input-label">文章地址</label><input id="note-slug" class="input" required pattern="[a-z0-9][a-z0-9-]{0,79}" maxlength="80" aria-describedby="slug-help"><p id="slug-help" class="editor-hint">使用小写字母、数字和短横线；发布后地址固定。</p></details>
        <div class="editor-pane-heading"><label for="note-body">正文 · Markdown</label><span id="word-count">0 字</span></div>
        <div class="format-toolbar" role="group" aria-label="插入格式"><button type="button" data-format="heading">标题</button><button type="button" data-format="bold">粗体</button><button type="button" data-format="list">列表</button><button type="button" data-format="link">链接</button><button type="button" data-format="code">代码</button></div>
        <textarea id="note-body" class="note-body-input" required maxlength="200000" placeholder="记录今天的发现…&#10;&#10;## 一个小标题&#10;&#10;写下正文，右侧会实时显示预览。" spellcheck="false"></textarea>
        <div class="editor-bottom"><span>支持标题、列表、链接、图片和代码块</span><div><button type="button" class="text-link" id="export-note">下载备份</button><button type="button" class="text-link" id="delete-draft">删除草稿</button></div></div>
      </form>
      <section class="card note-preview" aria-label="实时预览"><div class="editor-pane-heading"><h2>实时预览</h2><span>读者看到的样子</span></div><p id="preview-meta" class="editor-hint"></p><h3 id="preview-title">未命名笔记</h3><p id="preview-description"></p><div id="preview-body" class="article-body markdown-body"><p>文字会在这里慢慢成形。</p></div></section>
    </section>
  </div>
  <dialog id="publish-dialog" class="dialog publish-dialog" lang="zh-CN" aria-labelledby="publish-title"><div class="dialog-heading"><h2 id="publish-title">发布这篇笔记</h2><button type="button" class="icon-button" data-close-dialog aria-label="关闭发布窗口">${icon('close')}</button></div><p class="muted">发布后，所有访客都能阅读。文章列表、搜索和 RSS 会一同更新。</p><p id="publish-summary" class="publish-summary"></p><form id="publish-form"><label for="github-token" class="input-label">GitHub 发布令牌</label><input type="password" id="github-token" class="input" required autocomplete="off" spellcheck="false" placeholder="粘贴你的 GitHub token" aria-describedby="token-help"><p id="token-help" class="editor-hint">令牌仅用于本次操作，不会保存。请在 GitHub 创建仅授权此仓库、Contents 为 Read and write 的令牌。</p><a class="text-link" href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">创建发布令牌 ${icon('diagonal')}</a><p class="editor-hint publish-target">发布位置：${escapeHtml(site.publishing.owner)}/${escapeHtml(site.publishing.repo)} · ${escapeHtml(site.publishing.branch)}</p><p id="publish-status" class="editor-notice" role="status" hidden></p><button type="submit" id="confirm-publish" class="button button-primary">确认发布</button></form></dialog>`;
}
